# Generated by Django 2.0.5 on 2018-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='year_rel',
            field=models.IntegerField(default='2018', max_length=4),
        ),
    ]
